name: Go Cover
author: Milad Irannejad
description: GitHub Action for running go test command, generating coverage reports, and sending coverage reports.
inputs:
  path:
    description: The root path of the directory containing Go files.
    required: false
    default: .
  codecov_token:
    description: The Codecov token for sending coverage reports.
    required: false
  codeclimate_reporter_id:
    description: The Code Climate test reporter ID for sending coverage reports.
    required: false
outputs:
  coverage_profile_file:
    description: The path to coverage profile file.
  coverage_report_file:
    description: The path to coverage report file.
runs:
  using: docker
  image: Dockerfile
branding:
  icon: umberella
  color: green
