name: ShellCheck
author: Milad Irannejad
description: GitHub action for linting shell scripts.
inputs:
  path:
    description: The path to a directory or file.
    required: false
    default: .
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.path }}
branding:
  icon: check
  color: purple
