name: Packer
on:
  push:
    paths:
      - 'packer/**'
jobs:
  packer:
    name: Test packer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Packer
        uses: ./packer
        with:
          args: validate -syntax-only ./packer/test/ubuntu.json
