name: Main
on: push
jobs:
  semver:
    name: Test semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SemVer
        uses: ./semver
        with:
          file: ./semver/test/VERSION
  shellcheck:
    name: Test shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck
        uses: ./shellcheck
        with:
          path: ./shellcheck/test
  go-cover:
    name: Test go-cover
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Go Cover
        uses: ./go-cover
        with:
          path: ./go-cover/test
  go-lint:
    name: Test go-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Go Lint
        uses: ./go-lint
        with:
          path: ./go-lint/test
  cherry:
    name: Test cherry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Cherry Build
        uses: ./cherry
        with:
          args: -version
  packer:
    name: Test packer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Packer
        uses: ./packer
        with:
          args: validate -syntax-only ./packer/test/ubuntu.json
  terraform:
    name: Test terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Terraform
        uses: ./terraform
        with:
          path: ./terraform/test
          args: validate
  vault:
    name: Test vault
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Vault
        uses: ./vault
        with:
          args: version
