name: Main
on: push
jobs:
  go-cover:
    name: Test go-cover
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Go Cover
        uses: ./go-cover
  shellcheck:
    name: Test shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck
        uses: ./shellcheck
        with:
          path: './shellcheck/test'
