name: Main
on: push
jobs:
  shellcheck:
    name: Test shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: ShellCheck
        uses: ./shellcheck
        with:
          path: './shellcheck/test'
