name: SemVer
on:
  push:
    paths:
      - 'semver/**'
jobs:
  semver:
    name: Test semver
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Semantic Versioning (text)
        uses: ./semver
        with:
          file: ./semver/test/text/VERSION
      - name: Semantic Versioning (json)
        uses: ./semver
        with:
          file: ./semver/test/json/package.json
