name: ShellCheck
on:
  push:
    paths:
      - 'shellcheck/**'
jobs:
  shellcheck:
    name: Test shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ./shellcheck
        with:
          path: ./shellcheck/test
