name: Terraform
on:
  push:
    paths:
      - 'terraform/**'
jobs:
  terraform:
    name: Test terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Terraform
        uses: ./terraform
        with:
          path: ./terraform/test
          args: validate
