name: Vault
on:
  push:
    paths:
      - 'vault/**'
jobs:
  vault:
    name: Test vault
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Vault
        uses: ./vault
        with:
          args: version
